; «klistenia1»  (to ".klistenia1")

; «.klistenia1»	(to "klistenia1")
; https://www.youtube.com/watch?v=KJGFZVGGNPs
; (find-youtubedl-links "~/videos/" "Faca_esses_5_Movimentos_Primais_para_ficar_Forte_Naturalmente_-_Iniciante" "KJGFZVGGNPs" ".mp4" "klistenia1")
(code-video "klistenia1video" "~/videos/Faca_esses_5_Movimentos_Primais_para_ficar_Forte_Naturalmente_-_Iniciante-KJGFZVGGNPs.mp4")
; (find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt")

(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "1:33" "bora começar a session primeira coisa")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "1:35" "que a gente vai fazer antes de começar")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "1:37" "de fato os movimentos é soltar um pouco")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "1:39" "o punho fortalecer o punho então durante")

(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "3:6" "aqui agora mesma ideia só que a gente")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "3:9" "vai fazer com punho com Doro da mão no")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "3:11" "chão com punho virado para baixo e aí")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "3:15" "mesma coisa vai na manha vai no seu")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "3:19" "limite não precisa forçar muito a gente")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "3:23" "tá aqui mais para cuidar do corpo do que")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "3:25" "para massacrar")

(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "4:16" "fazer em formas de")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "4:18" "travessia ou não você pode ficar meio")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "4:21" "que no mesmo lugar mas de forma de")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "4:23" "travessia vai ser mais interessante para")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "4:25" "esses primeiros que eu vou mostrar o")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "4:27" "primeiro que a gente vai fazer é o Av")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "4:29" "tru Como que funciona esse movimento")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "4:33" "você vai achar aqui um lugar para")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "4:35" "começar vai dar um passo e vai tocar lá")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "4:39" "no chão e aí nem precisa subir tudo dá")

(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "6:29" "vai pro caminhada do Pato pra caminhada")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "6:32" "do pato que é uma caminhada nessa")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "6:36" "posição aqui mais baixa quase que um uma")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "6:40" "cocoras mas a gente vai ir da cocoras")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "6:44" "passiva PR uma cocoras ativa e caminhar")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "6:48" "nessa direção então daqui eu vou ativar")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "6:53" "transferir o peso tô aqui na cocos né")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "6:56" "vou transferir o peso para uma perna")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "7:0" "se você precisar pode usar a mão vou dar")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "7:3" "um passo desse passo eu vou transferir o")

(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "8:44" "agora a gente vai fazer o último desse")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "8:47" "estilo de travessia que é simplesmente")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "8:50" "andar na")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "8:51" "quadrupedia então nessa posição aqui")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "8:55" "você vai andar de uma forma contra")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "8:58" "lateral que é exatamente como a gente")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "9:1" "anda em pé também o que que significa")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "9:3" "isso significa que um membro vai andar")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "9:8" "de forma conjunta com o membro oposto Ou")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "9:12" "seja eu tô aqui na posição da")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "9:15" "quadrupedia e eu vou mão direita pé")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "9:20" "esquerdo mão esquerda pé direito e eu tô")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "9:24" "aqui andando numa relação contr")

(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:4" "agora vamos fazer duas explorações PR")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:7" "fechar aí o nosso treino a primeira")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:10" "exploração vai ser o seguinte da posição")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:13" "da")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:14" "quadrupedia você vai encontrar formas de")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:19" "virar a sua barriga para cima e virar")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:22" "sua barriga para baixo então se eu t")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:25" "aqui nessa")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:26" "posição eu vou encontrar uma forma")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:30" "de apontar a barriga para cima e apontar")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:35" "a barriga para baixo de")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:37" "novo apontei barriga para")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "11:40" "cima apontei a barriga para baixo Beleza")

(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:16" "de movimento Primal que a gente vai")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:18" "fazer vamos brincar um pouco mais com")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:21" "essa transferência de peso então virar a")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:24" "barriga para cima e a barriga para baixo")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:26" "a gente fez de forma um pouco mais")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:29" "dinâmica agora a gente quer construir um")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:32" "pouquinho mais de força um pouquinho")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:34" "mais de estabilidade Beleza então nesse")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:38" "como que vai funcionar durante esse 1")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:40" "minuto e meio você vai começar contra")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:45" "lateral")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:47" "então mão eu tô aqui nesse caso mão")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:50" "esquerda pé direito eu vou botar a minha")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:56" "outra mão no")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "14:57" "chão e e depois vou para uma relação IPS")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "15:1" "lateral agora eu tô mão direita pé")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "15:3" "direito e agora eu coloco o a perna no")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "15:7" "chão e fico contra lateral de novo e aí")
(find-fline "~/transcripts/klistenia1-KJGFZVGGNPs.txt" "15:11" "Eu repito Então vou mão IPS")
