;;                        _             _           _ _ 
;;  _ __ ___   __ _ _ __ | |_   _ _ __ | |__   __ _| | |
;; | '_ ` _ \ / _` | '_ \| | | | | '_ \| '_ \ / _` | | |
;; | | | | | | (_| | | | | | |_| | |_) | | | | (_| | | |
;; |_| |_| |_|\__,_|_| |_|_|\__, | .__/|_| |_|\__,_|_|_|
;;                          |___/|_|                    
;; 
; «thoughtpatterns»  (to ".thoughtpatterns")

; «.thoughtpatterns»	(to "thoughtpatterns")
; (find-daily "16-01-2025.org" ".mind-sweep-madrugada" "Outra coisa importantíssima tem me parecido ser essa ideia de mapear as coisas da minha vida")
; 
; (find-youtubedl-links "~/videos/" "{title}" "ME9xBGvhWuw" "{ext-}" "manlyphall-thoughpatterns")
(code-youtubevideo "manlyphall-thoughpatterns" "ME9xBGvhWuw" "{title}")
; (find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt")

(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:29" "religion presents us with abstract")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:33" "virtues")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:36" "religion provides us with a concept of")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:39" "an invisible causal universe beyond our")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:43" "perceptions")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:44" "it also populates this universe with")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:47" "beings invisible to us")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:50" "and the whole situation sums up in a")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:53" "very simple thought namely that religion")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:56" "deals with things we cannot see")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "17:59" "and so-called materialism deals with")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:03" "things we can see")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:06" "perfectly possible to see the house we")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:08" "are building")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:09" "it is perfectly possible to count the")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:12" "shares of stock that we own")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:14" "but it is not possible to actually")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:17" "factually estimate the nature of the")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:21" "spiritual World in which we live")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:24" "this world is shut from us because we do")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:28" "not possess the extra sensory")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:30" "perceptions necessary to make an")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:34" "invisible spiritual cause of Life")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:36" "visible and tangible to our common")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:39" "everyday living")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:41" "this place is all the advantage in the")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:45" "hands of the materialist")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:47" "whatever he is doing you can see he can")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:50" "see the Laboratories produce these")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:53" "experiments")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:54" "so we have facts Gatherings all the time")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "18:57" "more and more facts and truths gradually")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "19:02" "disappearing")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "19:04" "this means that there is a conflict")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "19:07" "between")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "19:09" "invisible principles")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "19:11" "and visible policies")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "19:14" "and as long as this conflict exists the")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "19:18" "individual is inevitably over influenced")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "19:21" "by the material policies")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "19:24" "because he can see them")

(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:17" "determine to change them")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:19" "there are responsibilities which we may")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:22" "not be able to dispose of but we can")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:25" "transmute them into opportunities")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:28" "we can do anything we want")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:31" "with the problems of the day if we will")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:34" "place inside of ourselves ourselves a")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:38" "major Rod a ruler by means of which we")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:43" "can measure the things that happen in")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:45" "daily life")
(find-fline "~/transcripts/manlyphall-thoughpatterns-ME9xBGvhWuw.txt" "45:47" "one of the situations that we all have")
