; «.scarlet-marton0»	(to "scarlet-marton0")

; «scarlet-marton0»  (to ".scarlet-marton0")
; (find-youtubedl-links "~/videos/" nil "-u-J9bLUSok" nil "scarletmarton0")
(code-youtubevideo "scarletmarton0" "-u-J9bLUSok" "{title}")
; (find-code-youtubevideo "scarletmarton0" "-u-J9bLUSok" "{title}")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt")

; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "se é niet começa por afirmar que para")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "tornar-se o que se é é preciso")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "sobretudo não suspeitar o que se")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "é aqui a divisa")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "socrática se acharia inteiramente")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "deslocada o filósofo revela então que na")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "sua vida jamais esteve consciente da")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "tarefa que se imporia a")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "Ele sem ter conhecimento dessa")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "tarefa seu instinto de")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "conservação organizava e hierarquizava")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "suas")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "competências é o que ele procura mostrar")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "na seguinte passagem cito")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "entrementes continua a crescer na")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "profundeza a ideia ideia entre aspas a")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "ideia")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "organizadora chamada a")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "dominar ela começa a")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "comandar lentamente conduz de volta dos")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "caminhos secundários e desvios prepara")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "qualidades e aptidões")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "isoladas que um dia se revelarão")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "indispensáveis como meios para o todo")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "ela configura uma a uma as faculdades")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "auxiliares antes mesmo de deixar")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "transpare")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "algo da tarefa dominante do fim da Meta")


; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:04" "em vários textos niet sustenta")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:08" "que o corpo consiste numa pluralidade de")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:11" "adversários as células assim como os")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:14" "tecidos e os órgãos estão em permanente")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:18" "combate de sorte que a todo momento")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:21" "qualquer elemento pode vir a predominar")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:24" "ou")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:26" "aperecer perspectiva a luta garante a")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:30" "permanência da mudança ela faz também")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:33" "com que se estabeleçam hierarquias")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:36" "vale insistir que a luta é sem trégua e")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:40" "sem termo desta arte as hierarquias")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:43" "nunca são definitivas Afinal é com")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:47" "processos de dominação que a vida se")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:49" "identifica é a essa mesma lógica que")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:53" "obedece o que niet chama de suas")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:56" "faculdades entre aspas na passagem de")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "36:59" "assomo que citamos acima então Ele")

; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:02" "defende a ideia que graças ao trabalho")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:05" "do instinto de conservação seus")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:07" "diferentes impulsos se organizam de")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:10" "forma que suas atividades se integrem")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:13" "uns se submetem a outros que por sua vez")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:16" "se acham subordinados a outros Ainda")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:21" "graças a essa organização hierárquica")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:25" "arranjando com os impulsos")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:28" "de disposição concordante e submetendo")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:31" "os que lhe são opostos um impulso")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:34" "predominante vem a coordenar todos os")
; (find-fline "~/transcripts/scarletmarton0--u-J9bLUSok.txt" "37:37" "demais e a impor-lhes uma direção Clara")

; (find-scarletmarton0video "37:58" "redefinindo por completo a noção")
; (find-scarletmarton0video "38:2" "de egoísmo ele vem recusar a concepção")
; (find-scarletmarton0video "38:6" "moderna de")
; (find-scarletmarton0video "38:7" "sujeito concebido como substrato que")
; (find-scarletmarton0video "38:11" "produz vários efeitos desenvolve")
; (find-scarletmarton0video "38:15" "diversas atividades e possui certas")
; (find-scarletmarton0video "38:18" "propriedades cito o sujeito não é nada")
; (find-scarletmarton0video "38:22" "além de uma")
; (find-scarletmarton0video "38:23" "ficção entendido como um todo")
; (find-scarletmarton0video "38:26" "independente completo idêntico a si")
; (find-scarletmarton0video "38:28" "mesmo permanente e unitário cito o ego é")
; (find-scarletmarton0video "38:33" "tão somente um embuste superior um")
; (find-scarletmarton0video "38:37" "ideal no quadro desse egoísmo sem Ego")
; (find-scarletmarton0video "38:41" "não há lugar para um sujeito que se")
; (find-scarletmarton0video "38:44" "mantém sempre o mesmo em sua")
; (find-scarletmarton0video "38:48" "individualidade enquanto força")
; (find-scarletmarton0video "38:51" "organizadora ou se se quiser enquanto")
; (find-scarletmarton0video "38:54" "ideia entre aspas chamada a dominar seu")
; (find-scarletmarton0video "38:57" "instinto de conservação fez em segredo o")
; (find-scarletmarton0video "39:1" "trabalho de formar uma configuração")
; (find-scarletmarton0video "39:3" "pulsional destinada à tarefa de")
; (find-scarletmarton0video "39:8" "transvalor os valores ")
